# Generated by Django 5.1.5 on 2025-02-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorielog',
            name='email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
    ]
