# Generated by Django 5.1.5 on 2025-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker2', '0002_calorielog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorielog',
            name='total_calories',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
