# Generated by Django 5.1.5 on 2025-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker2', '0004_totalcalories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcalories',
            name='user',
        ),
        migrations.AddField(
            model_name='totalcalories',
            name='email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
    ]
